# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 30
      max: 1000
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: autumn-web
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: autumn # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  freemarker:
    suffix: .html
    request-context-attribute: request

autumn:
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
  database: mysql
  table:
    auto: update
    init: true
    pack: cn.org.autumn.modules

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.org.autumn.modules.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置
    logic-delete-value: -1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

logging:
  level: info
  level.cn.org.autumn: info
  level.com.aliyun.oss: fatal
  level.springfox.documentation: fatal
  level.org.quartz: warn
  level.org.springframework: info
  #  level.org.springframework.web: warn
  #  level.org.springframework.jmx: warn
  #  level.org.springframework.boot.web: warn
  #  level.org.springframework.boot.web.servlet: warn
  level.org.springframework.boot.web.embedded: info
  level.com.alibaba.druid: info
  level.org.mybatis.spring: info
  level.org.apache.tomcat: info
  level.org.apache.catalina: info
  level.sun.rmi.transport.tcp: info

  file:
    name: file.log
    path: logs/

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapperLocations: classpath:mapper/**/*.xml


